services:
  api:
    container_name: rdev-go-api-template-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - rdev-go-api-template-network

  migrate:
    container_name: rdev-go-api-template-migrate
    build:
      context: .
      dockerfile: Dockerfile
    command: ["migrate"] 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rdev-go-api-template-network

  db:
    container_name: rdev-go-api-template-db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rdev-go-api-template-network

  redis:
    image: redis:7-alpine
    container_name: rdev-go-api-template-redis
    ports:
      - "6378:6379"
    networks:
      - rdev-go-api-template-network

  mailhog:
    container_name: rdev-go-api-template-mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - rdev-go-api-template-network

networks:
  rdev-go-api-template-network:
    driver: bridge
