CREATE TABLE IF NOT EXISTS users(
    id bigint generated always as identity primary key,
    first_name varchar(45),
    last_name varchar(45),
    email varchar(255) not null unique,
    username varchar(255) not null unique,
    password text not null,
    user_type varchar(45),
    addr1 varchar(255),
    addr2 varchar(255),
    city varchar(255),
    postal varchar(255),
    latitude numeric(9,6),
    longitude numeric(10,6),
    is_loggedin boolean default false,
    status varchar(1) not null default 'A',
    uuid UUID not null default gen_random_uuid(),
    created_at timestamptz not null default NOW(),
    updated_at timestamptz default NOW(),
    deleted_at timestamptz default null
)