CREATE TABLE IF NOT EXISTS jobs(
    id bigint generated always as identity primary key,
    service_id bigint not null,
    provider_id bigint not null,
    client_id bigint not null,
    technician_id bigint default null,
    name varchar(45),
    description text,
    job_reference varchar(150),
    job_status varchar(15),
    scheduled_at timestamptz default null,
    started_at timestamptz default null,
    completed_at timestamptz default null,
    unit_count int,
    unit_type varchar(45),
    total_price bigint default 0,
    addr1 varchar(255),
    addr2 varchar(255),
    city varchar(45),
    postal varchar(45),
    latitude numeric(9,6),
    longitude numeric(10,6),
    status varchar(1) not null default 'A',
    uuid UUID not null default gen_random_uuid(),
    created_at timestamptz not null default NOW(),
    updated_at timestamptz default NOW(),
    deleted_at timestamptz default null,

    constraint fk_job_provider foreign key (provider_id) references providers (id),
    constraint fk_job_service_type foreign key (service_id) references service_types (id),
    constraint fk_job_user_client foreign key (client_id) references users (id),
    constraint fk_job_user_technician foreign key (technician_id) references users (id)
)